name: checks

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: agent/go.mod
          cache-dependency-path: agent/go.mod

      - name: Install dependencies
        run: npm ci

      - name: Check web app
        run: npm run check

      - name: Test device agent
        working-directory: agent
        run: go test ./...
